migrating CI from ubuntu-20.04 to ubuntu-24.04

diff --git a/.github/workflows/amc_ci.yml b/.github/workflows/amc_ci.yml
--- a/.github/workflows/amc_ci.yml
+++ b/.github/workflows/amc_ci.yml
@@ -20,7 +20,7 @@ jobs:
 
   test_and_document:
     name: Test And Generate Documentation
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-24.04
     steps:
 
       # This step checks out a copy of your repository.
@@ -30,7 +30,7 @@ jobs:
 
       - uses: actions/setup-python@v2
         with:
-          python-version: 3.8
+          python-version: 3.12
 
       - name: Install dependencies
         run: |
@@ -38,6 +38,13 @@ jobs:
           sudo apt-get install doxygen doxygen-doc doxygen-latex doxygen-gui graphviz ghdl
           python -m pip install --upgrade pip
           pip install flake8
+
+      - name: Check for trailing whitespace
+        run: |
+          if grep -rnI '[[:blank:]]$' --include=\*.{vhd,v,tcl,py,yaml,xdc} .; then
+            echo "Error: Trailing whitespace found in the repository!"
+            exit 1
+          fi
 
       - name: VHDL Syntax Check
         run: |
